# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required
cache: packages

install: travis_wait 20 mvn install

r_packages:
  - covr
after_success:
  - Rscript -e 'covr::codecov()'
