# Sample .travis.yml for R projects

# blocklist
#branches:
#  except:
#  - appveyor

language: r
warnings_are_errors: true
sudo: required
cache: packages

r_packages:
  - covr
after_success:
  - Rscript -e 'covr::codecov(quiet=FALSE)'
