# Sample .travis.yml for R projects

# blocklist
#branches:
#  except:
#  - appveyor

language: r
warnings_are_errors: true
sudo: required
dist: trusty
cache: packages

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

r_packages:
  - covr

r_github_packages:
  - jimhester/lintr

after_success:
  - Rscript -e 'covr::codecov(quiet=FALSE)'
