---
title: "knmitransformer - standard stations"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{StandardStations}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r LoadLibraries, include=FALSE}
library(knmitransformer)
```

## Precipitation:
```{r precipSelection}
subscenario <- "centr"
input       <- system.file("refdata",
                           "KNMI14____ref_rrcentr___19810101-20101231_v3.2.txt",
                           package="knmitransformer")
ofile       <- "tmp.txt" # output file - used only temporary
scenario    <- "GL"
horizon     <- 2030
```

```{r precipTransformation}
futPrecip <- TransformPrecip(input=input, ofile=NA,
                             scenario=scenario, horizon=horizon,
                             subscenario=subscenario)
```

```{r precipShowResult}
head(futPrecip[, 1 : 5])
```

## Temperature:
```{r tempSelection}
var        <- "tg"
input      <- system.file("refdata",
                          "KNMI14____ref_tg___19810101-20101231_v3.2.txt",
                          package="knmitransformer")
regio.file <- "stationstabel"
scenario   <- "GL"
horizon    <- 2030
```

```{r tempTransformation}
futTemp <- TransformTemp(input=input, ofile=NA,
                         scenario=scenario, horizon=horizon,
                         var=var, regio.file=regio.file)
```

```{r tempShowResult}
head(futTemp[, 1 : 5])
```

## Radiation:
```{r radSelection}
input      <- system.file("refdata",
                        "KNMI14____ref_rsds___19810101-20101231_v3.2.txt",
                        package="knmitransformer")
scenario   <- "GL"
horizon    <- 2030
```

```{r radTransformation}
futRad <- TransformRadiation(input=input, ofile=NA,
                         scenario=scenario, horizon=horizon)
```

```{r radShowResult}
head(futRad[, 1 : 5])
```

## Makkink evaporation:
```{r evapSelection}
input_tg   <- system.file("refdata",
                          "KNMI14____ref_tg___19810101-20101231_v3.2.txt",
                          package="knmitransformer")
input_rsds <- system.file("refdata",
                        "KNMI14____ref_rsds___19810101-20101231_v3.2.txt",
                        package="knmitransformer")
scenario   <- "GL"
horizon    <- 2030
regio.file <- "stationstabel"
```

```{r evapTransformation}
futEvap <- TransformEvap(input_tg=input_tg, input_rsds=input_rsds, ofile=NA,
                         scenario=scenario, horizon=horizon,
                        regio.file="stationstabel")
```

```{r evapShowResult}
head(futEvap[, 1 : 5])
```