// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// DeterminePowerLawExponentCpp
double DeterminePowerLawExponentCpp(NumericVector Xm, double qfut, double qobs, double mfut);
RcppExport SEXP knmitransformer_DeterminePowerLawExponentCpp(SEXP XmSEXP, SEXP qfutSEXP, SEXP qobsSEXP, SEXP mfutSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type Xm(XmSEXP);
    Rcpp::traits::input_parameter< double >::type qfut(qfutSEXP);
    Rcpp::traits::input_parameter< double >::type qobs(qobsSEXP);
    Rcpp::traits::input_parameter< double >::type mfut(mfutSEXP);
    __result = Rcpp::wrap(DeterminePowerLawExponentCpp(Xm, qfut, qobs, mfut));
    return __result;
END_RCPP
}
