# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DeterminePowerLawExponentCpp <- function(Xm, qfut, qobs, mfut) {
    .Call('knmitransformer_DeterminePowerLawExponentCpp', PACKAGE = 'knmitransformer', Xm, qfut, qobs, mfut)
}

