# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DeterminePowLawExponentCpp <- function(Xm, qfut, qobs, mfut) {
    .Call('knmitransformer_DeterminePowLawExponentCpp', PACKAGE = 'knmitransformer', Xm, qfut, qobs, mfut)
}

